# Generated by Django 5.2.12 on 2026-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient'), ('DRIVER', 'Ambulance Driver')], default='PATIENT', help_text='Designates the role of this user in the system.', max_length=20),
        ),
    ]
